### PR TITLE
Bug/prompt user about unsaved data 54

### LINKED ISSUE #54: Prompt user about unsaved data
Usability tests showed that some people don't add the last person they want to add to the nobt throw the '+' button but rather click straight on the 'Create Nobt' button. In the current implementation, the app just takes the uncompleted list and therefore creates the nobt without the last person the user actually wanted to add.

We should implement a prompt as soon as the user clicks the button and ask them, whether they also want to add the last user to the nobt before actually creating the nobt.

### PR DESCRIPTION
**Pull request by duffleit**
Fixes #54 (Usability issue).

Users are not able to create the nobt, as long as the "name"-input is not empty.

### CODE REVIEW

File: src/components/SingleInputInlineForm/SingleInputInlineForm.js [hunk 1]
```diff
@@ -10,43 +10,30 @@ import classnames from "classnames";
 
 export default class SingleInputInlineForm extends React.Component {
```
Comment (thomaseizinger) [inline src/components/SingleInputInlineForm/SingleInputInlineForm.js]: As we are now no longer really using this component as it was intended, I would suggest to not use the component here at all and simply display a regular input field (and skip the old '+' button). What do you think?

File: src/routes/CreateNobt/routes/members/components/AddMembersForm/AddPersonButtonTheme.scss [hunk 2]
```diff
@@ -0,0 +1,6 @@
+.button {
```
Comment (thomaseizinger) [inline src/routes/CreateNobt/routes/members/components/AddMembersForm/AddPersonButtonTheme.scss]: If you apply the customization of the ´text-transform´ property via regular `className` styling, you could reuse the theme of the other button and avoid the duplication.
There is also a theme-merger in the `styles` folder that you could use if you want to the keep the styling of this button in a dedicated file.

File: src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js [hunk 3]
```diff
@@ -19,6 +20,17 @@ import CreateNobtProgressBar from "../../components/CreateNobtProgressBar"
 
 class AddMembersForm extends React.Component {
 
+  state = {
+    memberToAdd: ""
```
Comment (thomaseizinger) [inline src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js]: Have you thought about moving this state to the redux store?
You could move all the conditional logic into selectors then. (and test it very easily!)

File: src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js [hunk 4]
```diff
@@ -33,7 +45,9 @@ class AddMembersForm extends React.Component {
 
           <SingleInputInlineForm
             className={styles.addMemberInputInlineForm}
-            onSubmit={this.props.addPerson}
+            onSubmit={this.handleOnNewMember}
```
Comment (thomaseizinger) [inline src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js]: As already mentioned above, this component does not longer really serve its job after this customization, I would just go for a regular `Input` field instead.

File: src/components/SingleInputInlineForm/SingleInputInlineForm.js (hunk 1 above)
Comment (duffleit) [reply src/components/SingleInputInlineForm/SingleInputInlineForm.js]: I think that even the pure composition still has its justification. I like it even better that the components now has no internal status anymore.

File: src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js (hunk 4 above)
Comment (thomaseizinger) [reply src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js]: The whole list of members is already in the store. Based on the complexity (conditional rendering) this state causes, I think moving it to the store would be good. Now, a lot of logic and complexity is contained in the render method of the page.

File: src/components/SingleInputInlineForm/SingleInputInlineForm.js (hunk 1 above)
Comment (thomaseizinger) [reply src/components/SingleInputInlineForm/SingleInputInlineForm.js]: Back when this component was created, the whole idea was to encapsulate this state, so it does not have to be duplicated on every usage. As you may have noticed during your refactoring, you now have to store the `value` in the parent component every time you use this component.
What it boils down to in this scenario is that you need to access the state of the input field before the form is submitted. This, in my opinion, simply makes the component unusable in this scenario in its current implementation. For the other usages however, it still makes sense. I'd say that changing a component because it does not fit in one scenario and thereby being forced to change other, completely unrelated code parts does not justify the change.
Additionally, without the internal state, this component is no longer a form as the name suggests. A form can be submitted to retrieve the entered values. 

I'd suggest to simply not use this component here but rather directly use the `Input` field from react-toolbox. As stated below, it is probably better anyway to move the state to the redux store in this scenario, as the relevance of this state is no longer limited to a local component but affects the whole page.

Comment (duffleit) [reply src/components/SingleInputInlineForm/SingleInputInlineForm.js]: I don't think the main purpose of components is to hide state. They simply provide aggregations of components which are used more than once. That’s why I would like to stay with it. 
I like the argumentation of "changing a component because it does not fit in one scenario" should be avoided. Still, a component is nothing else then a dependency. And that's the price you must pay for dependencies. But, I still prefer this over duplication.

File: src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js (hunk 4 above)
Comment (duffleit) [reply src/routes/CreateNobt/routes/members/components/AddMembersForm/AddMembersForm.js]: Kk, I'll move it into the store.

File: src/components/SingleInputInlineForm/SingleInputInlineForm.js (hunk 1 above)
Comment (thomaseizinger) [reply src/components/SingleInputInlineForm/SingleInputInlineForm.js]: Not of every component but it was one of the primary reasons for this one.

Maybe the component could be refactored to a compound component in order to allow better customization. IMO there are just too many props on this component and it really just combines an Input with a Button. Now that it also lost its state, I cannot even provide real functionality. I would suggest a pairing session for refactoring the component because I am really not satisfied with the way it is now.

**Comment by thomaseizinger** [comment]
I continued to work on this locally but ran into some issues with the usage of the SingleInputInlineForm on the newBill page. The newBill page though will eventually be replaced with a wizard, "solving" this issue. Therefore, I did not complete my changes here but rather started working on the newBill wizard.

**Comment by thomaseizinger** [comment]
I finished the refactoring and removed the SingleInputInlineForm completely. See the commit messages for details.
The UI now looks like this: (a bit different, but mostly the same)

new-add-member-form
add-bill-form

**Comment by thomaseizinger** [comment]
I was finally able to align the styling of list items. Pretty though but I managed to do it in a lean way! We should merge this soon, as it is quite a UX issue.
